version: '3'
services:
  db:
    image: percona:8.0.22-13-centos
    environment:
      MYSQL_ROOT_PASSWORD: qa_site
      MYSQL_DATABASE: qa_site
      MYSQL_USER: qa_site
      MYSQL_PASSWORD: qa_site
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080