server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qa_site # create database manually with name qasite
    username: qa_site # you can use your default user, such as mysql or root
    password: qa_site # and default user's password
  jpa:
    show-sql: true # shows the generated SQL from the HQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # create, update, create-drop, validate, none

jwt:
  key: f6cf0b0044d6f75d024aaf55a49f206be9276b9d42b6f493c229e33c9c66fb30f8f410adcc1cad4b8ac346d6d8580c73ba0ee90003b0c24faf7d15c6f2bf76a5
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect